# Generated by Django 5.1.2 on 2024-11-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='desciption',
            new_name='description',
        ),
    ]
